language: python
python:
- 3.6
env:
  matrix:
  - ETCD_VERSION=v3.1.10
  - ETCD_VERSION=v3.3.1
install:
- pip install -U tox tox-travis codecov
- curl -L https://github.com/coreos/etcd/releases/download/$ETCD_VERSION/etcd-$ETCD_VERSION-linux-amd64.tar.gz
  -o etcd-$ETCD_VERSION-linux-amd64.tar.gz
- tar xzvf etcd-$ETCD_VERSION-linux-amd64.tar.gz
- export PATH=$PATH:etcd-$ETCD_VERSION-linux-amd64
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  user: andreycizov
  password:
    secure: VugJJed3+8ek1tjZLeDHT0VPTG5pt2sy6gab7y3AJNbv04rri5+0CDK1SxmY4G0RCC+aIuCHzu3j6JCKlNqkZsJyZZcYkO68UUm9iOmi1mCHYVHLiFbbunS8Gv3rtXKD1gsWXtApn80yyV7Pe9Ew5fDNGL4JGJAtMuEtir7LWXCJ68cu68NTSUJH1ZVD8+lqmq9Dn2psZ3Ybb17viev6DXhhfNiJhsSTbZYIaXIQW6+kwpTxdlBF8Fb/AwjP8oO6b+OONU9NUEOvUOsAlZfp+IsLg20KgjUlOj+MLf67YFJwQpRjoS/UOHDkjKvM4bu5fE1bM+mj8tQ9eoLmddPRiA60TQV+PA4ZiatxsO/c3ZEoYaco9U8GCGDUZNEjNkUAmgs5239eLKShOVORNJFGiOZp8Xl6RfTiiVhUkR4XXCOjbpujq5mpfy97/hRL9qVQw+WxCLil8ndPTveGXE14Zobp5sIVsH55S7x4de1t3j+2wbeW7d3ZTzHcMJsR/e6M1kcP+NwCo1ws85fJqHsti6o1E6Cww1w/lIE72qYODmi8aqLXOXmC3oHTzet+Yl0W1ja0iV7VxefLvvX9z4GWjSc0JXNm2Fx/Y4RAV5Sl3oyxv1ItcZc8lHYid5GLdDlPEqvNLOdMJ5GCPPpPx/fKZ3ajOtNnGTHTXmnRRqAnufQ=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: andreycizov/python-etcd3-wrapper
